name: 'ci'
on:
  workflow_call:

jobs:
  sample:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is a CI workflow."

#   # Example job for Node.js projects
#   node:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v5
#       - name: Use Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: '20.x'
#       - run: npm ci
#       - run: npm run build
#       - run: npm test
